application: bnuxiaoq
version: alpha
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /init
  script: init.app
  login: admin

- url: /topten(.*)
  script: topten.app
  login: admin

- url: /weather(.*)
  script: weather.app
  login: admin

- url: /
  script: main.app