application: bnuxiaoq
version: alpha
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/img
  static_dir: static/img

- url: /init
  script: init.app
  login: admin

- url: /topten(.*)
  script: topten.app
  login: admin

- url: /weather(.*)
  script: weather.app
  login: admin

- url: /classroom(.*)
  script: classroom.app
  login: admin

- url: /pattern(.*)
  script: pattern.app
  login: admin

- url: /(.*)
  script: main.app